spring:
  datasource:
    url: jdbc:mysql://seoul-dev-lightsaber-alarm-auroradb01-cluster.cluster-clc1budgyiqp.ap-northeast-2.rds.amazonaws.com/lsaber10002
    username: W_ALM
    password: tpdlqj20!&devALRM
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE